### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by hhhhwill** [itwanger/paicoding#83]
报错内容如下：
vlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at com.github.paicoding.forum.web.QuickForumApplication.main(QuickForumApplication.java:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.jdbc.datasource.init.DataSourceInitializer]: Factory method 'dataSourceInitializer' threw exception; nested exception is org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [select * from DATABASECHANGELOG where ID='00000000000020' limit 1;]; nested exception is java.sql.SQLSyntaxErrorException: Table 'pai_coding.databasechangelog' doesn't exist
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 24 common frames omitted
Caused by: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [select * from DATABASECHANGELOG where ID='00000000000020' limit 1;]; nested exception is java.sql.SQLSyntaxErrorException: Table 'pai_coding.databasechangelog' doesn't exist
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1541)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:393)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:465)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:475)
	at org.springframework.jdbc.core.JdbcTemplate.queryForList(JdbcTemplate.java:525)
	at com.github.paicoding.forum.web.config.init.ForumDataSourceInitializer.needInit(ForumDataSourceInitializer.java:87)
	at com.github.paicoding.forum.web.config.init.ForumDataSourceInitializer.dataSourceInitializer(ForumDataSourceInitializer.java:49)
	at com.github.paicoding.forum.web.config.init.ForumDataSourceInitializer$$EnhancerBySpringCGLIB$$18a299e5.CGLIB$dataSourceInitializer$0(<generated>)
	at com.github.paicoding.forum.web.config.init.ForumDataSourceInitializer$$EnhancerBySpringCGLIB$$18a299e5$$FastClassBySpringCGLIB$$791f1362.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at com.github.paicoding.forum.web.config.init.ForumDataSourceInitializer$$EnhancerBySpringCGLIB$$18a299e5.dataSourceInitializer(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 25 common frames omitted
Caused by: java.sql.SQLSyntaxErrorException: Table 'pai_coding.databasechangelog' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1201)
	at com.zaxxer.hikari.pool.ProxyStatement.executeQuery(ProxyStatement.java:110)
	at com.zaxxer.hikari.pool.HikariProxyStatement.executeQuery(HikariProxyStatement.java)
	at org.springframework.jdbc.core.JdbcTemplate$1QueryStatementCallback.doInStatement(JdbcTemplate.java:452)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:381)
	... 40 common frames omitted

Process finished with exit code 0

Table 'pai_coding.databasechangelog' doesn't exist该如何解决？
![Uploading Snipaste_2024-08-12_15-25-16.png…]()

**Comment by liuyueyi** [comment]
删除 pai_coding 数据库，然后重新启动

**Comment by hhhhwill** [comment]
> 删除 pai_coding 数据库，然后重新启动

谢谢，已经解决问题了
昨天晚上遇到了一个问题是 Public Key Retrieval is not allowed，然后自己搜了下，yml文件中url修改为url: jdbc:mysql://localhost:3306/${database.name}?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=TRUE才解决Public Key Retrieval is not allowed的问题了，然后今天中午才遇到上述问题，删除pai_coding数据集并重新启动后解决，再次感谢！

**Comment by hhhhwill** [comment]
> 删除 pai_coding 数据库，然后重新启动

还有个小问题，
![Snipaste_2024-08-12_18-16-09](https://github.com/user-attachments/assets/a6033e60-4436-4c6f-8ede-4f02240b3e35)
我取消type: com.alibaba.druid.pool.DruidDataSource的注释后下载了DruidDataSource的maven包，但是下面的内容还是红色的，虽然不影响使用但还是蛮好奇的

**Comment by ymqzuishuai** [comment]
谢谢你顶针同学，帮大忙了
